version: 2.1

orbs:
  architect: giantswarm/architect@2.4.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: cluster-api-provider-vsphere
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/cluster-api-vsphere-controller"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
